from numseq import *

# print(naturals(10))
# print(naturals0(10))
# print(odd_numbers_up_to(11))
# print(first_odd_numbers(4))
# print(even_numbers_up_to(11))
# print(first_even_numbers(10))
# print(perfect_squares_up_to(100))
# print(first_perfect_square_numbers(10))
# print(perfect_cubes_up_to(130))
# print(first_perfect_cube_numbers(5))
# print(triangular_numbers_up_to(50))
# print(first_triangular_numbers(10))
# print(tetrahedral_numbers_up_to(100))
# print(first_tetrahedral_numbers(4))
# print(prime_numbers_up_to(100))
# print(first_prime_numbers(10))
# print(fibonacci_numbers_up_to(10))
# print(first_fibonacci_numbers(10))
# print(lucas_numbers_up_to(10))
# print(first_lucas_numbers(10))
# print(catalan_numbers_up_to(100))
# print(first_catalan_numbers(10))
# print(factorial_numbers_up_to(500))
# print(first_factorial_numbers(10))
# print(padovan_numbers_up_to(11))
# print(first_padovan_numbers(10))
# print(perrin_numbers_up_to(20))
# print(first_perrin_numbers(10))
# print(motzkin_numbers_up_to(2200))
# print(first_motzkin_numbers(5))
# print(tribonacci_numbers_up_to(30))
# print(first_tribonacci_numbers(5))
# print(armstrong_numbers_up_to(500))
# print(first_armstrong_numbers(10))
# print(perfect_numbers_up_to(2000))
# print(first_perfect_numbers(1))
# print(collatz_sequence(10))

print(harshad_numbers_up_to(20))
print(first_harshad_numbers(5))
print(hamming_numbers_up_to(20))
print(first_hamming_numbers(4))