from numseq import *

print(naturals(10))
print(naturals0(10))
print(odd_numbers_up_to(11))
print(first_odd_numbers(4))
print(even_numbers_up_to(11))
print(first_even_numbers(10))
print(perfect_squares_up_to(100))
print(first_perfect_square_numbers(10))
print(perfect_cubes_up_to(130))
print(first_perfect_cube_numbers(5))
print(triangular_numbers_up_to(50))
print(first_triangular_numbers(10))
print(tetrahedral_numbers_up_to(100))
print(first_tetrahedral_numbers(4))
print(prime_numbers_up_to(100))
print(first_prime_numbers(10))
print(fibonacci_numbers_up_to(10))
print(first_fibonacci_numbers(10))
print(lucas_numbers_up_to(10))
print(first_lucas_numbers(10))
print(catalan_numbers_up_to(100))
print(first_catalan_numbers(10))